services:
  php-app:
    build: .
    container_name: php-app
    ports:
      - "${APP_PORT:-8080}:80"
    volumes:
      - .:/var/www/html
      - ./public/uploads:/var/www/html/public/uploads
      - node_modules:/var/www/html/node_modules
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
      - APP_DEBUG=${APP_DEBUG:-true}
      - APP_NAME=${APP_NAME}
      - APP_ENV=${APP_ENV:-development}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - VITE_DEV_SERVER=http://vite:3000
    depends_on:
      - mariadb
      - vite
    restart: unless-stopped
    networks:
      - php-app-network

  vite:
    build: .
    container_name: php-app-vite
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    ports:
      - "3000:3000"
    volumes:
      - .:/var/www/html
      - node_modules:/var/www/html/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - php-app-network
    restart: unless-stopped

  mariadb:
    image: mariadb:10.11
    container_name: php-app-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "${DB_PORT_EXTERNAL:-3306}:3306"
    restart: unless-stopped
    networks:
      - php-app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: php-app-phpmyadmin
    environment:
      - PMA_HOST=${DB_HOST}
      - PMA_PORT=${DB_PORT}
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT:-8081}:80"
    depends_on:
      - mariadb
    restart: unless-stopped
    networks:
      - php-app-network

volumes:
  mariadb_data:
  node_modules:

networks:
  php-app-network:
    driver: bridge

